
platform :ios, '9.0'
#use_frameworks

def pods
    pod 'AFNetworking', '3.2.1'
    pod 'SDWebImage', '4.4.2'
    pod 'Masonry', '1.1.0'
    pod 'MBProgressHUD', '1.1.0'
    pod 'MJRefresh', '3.1.15.3'
    pod 'IQKeyboardManager', '6.1.1'
    pod 'MJExtension', '3.0.15.1'
    pod 'DZNEmptyDataSet'
end

target 'CJHGoggle' do
    pods
end
